---
abstract: 'Module for manipulating permutations '
author:
  - 'Stefan Petrea <stefan.petrea@gmail.com>'
generated_by: 'Dist::Zilla version 1.093220'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CM-Permutation
requires:
  Algorithm::Permute: 0
  Carp: 0
  GraphViz: 0
  List::AllUtils: 0
  Math::BigInt: 0
  Moose: 0
  Storable: 0
  Test::More: 0
  Text::Table: 0
  perl: 5.010000
version: 0.05
