---
abstract: 'Module for manipulating permutations '
author:
  - 'Stefan Petrea <randomcoder1@gmail.com>'
build_requires: {}
configure_requires:
  ExtUtils::MakeMaker: 6.30
dynamic_config: 0
generated_by: 'Dist::Zilla version 4.200011, CPAN::Meta::Converter version 2.110930'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: CM-Permutation
requires:
  Acme::AsciiArt2HtmlTable: 0
  Algorithm::Permute: 0
  Bit::Vector: 7.1
  Carp: 0
  GraphViz: 0
  List::AllUtils: 0.02
  Math::BigInt: 0
  Math::Polynomial: 1.002
  Moose: 0.92
  MooseX::Role::Parameterized: 0.17
  OpenGL: 0.64
  Params::Validate: 0.94
  Storable: 0
  Test::Deep: 0.106
  Test::More: 0
  Text::Table: 1.114
  overload: 0
version: 0.9
